version: "3.8"

services:
  app:
    build: .
    container_name: expenses_app
    env_file:
      - .env
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always
