version: "3.9"

services:
  app:
    build: .
    container_name: expenses_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
      - nginx
    networks:
      - expenses_network

  nginx:
    image: nginx:alpine
    container_name: pesayangu_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/usr/src/app:ro
    networks:
      - expenses_network

  postgres:
    image: postgres:15-alpine
    container_name: pesayangu_postgres
    restart: always
    environment:
      POSTGRES_DB: pesayangu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expenses_network

volumes:
  postgres_data:

networks:
  expenses_network:
    driver: bridge
