version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expenses_net
    env_file:
      - .env

  backend:
    build:
      context: ./pesayangu
      dockerfile: Dockerfile
    image: codewithmac/expenses-backend:latest
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    networks:
      - expenses_net
    env_file:
      - .env

  frontend:
    build:
      context: ./ExpensesTS
      dockerfile: Dockerfile
    image: codewithmac/expenses-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    networks:
      - expenses_net

  nginx:
    image: nginx:alpine
    container_name: expenses_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ExpensesTS/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/expenses.seranise.co.tz:/etc/letsencrypt/live/expenses.seranise.co.tz:ro
      - /etc/letsencrypt/archive/expenses.seranise.co.tz:/etc/letsencrypt/archive/expenses.seranise.co.tz:ro
    depends_on:
      - frontend
      - backend
    networks:
      - expenses_net

volumes:
  postgres_data:

networks:
  expenses_net:
    driver: bridge
